remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme      # keeps the Cayman theme working
  - jekyll-seo-tag           # emits SEO + verification meta tags

google_site_verification: "haeA8HMPYrFnd9nO1bBQyyL3OggGaoehCa5VHs96Qjy"
