remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme      # needed for the remote theme
  - jekyll-seo-tag           # needed to emit the meta tag

google-site-verification content: "haeA8HWPYrfnd9nO1BbQyyL30qgGaoehCa5VHs96QiY"
