# ---------- site & theme ----------
remote_theme: pages-themes/midnight@v0.2.0

url: "https://loud-whisper.github.io"
baseurl: "/inner-neutrality"

# ---------- plugins ----------
plugins:
  - jekyll-remote-theme
  # - jekyll-seo-tag  # Commented out this line
  - jekyll-sitemap

# GitHub Pages needs this key if you define plugins
whitelist:
  - jekyll-remote-theme
  # - jekyll-seo-tag  # Commented out this line
  - jekyll-sitemap

# ---------- Google Search Console ----------
google_site_verification: "PvvW0mLDW7WvV6ttqxu-76YGRguZB2jeSs3GqYW1MbQ"
